# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - pge-nrg-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn/cache
            .yarn/unplugged
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Create deployment package
        run: |
          # Create a clean deployment directory
          rm -rf deployment
          mkdir -p deployment
          
          # Copy only the necessary files
          cp host.json deployment/
          cp package.json deployment/
          cp yarn.lock deployment/
          cp .funcignore deployment/
          
          # Copy only the compiled function files
          for dir in */; do
            if [[ -f "$dir/function.json" ]]; then
              mkdir -p "deployment/$dir"
              cp "$dir/function.json" "deployment/$dir/"
              if [[ -d "dist/$dir" ]]; then
                cp -r "dist/$dir"/* "deployment/$dir/"
              fi
            fi
          done

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deployment

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'pge-nrg-api'
          slot-name: 'Production'
          package: '.'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5F2BDE1981AD4BC1AB87F222F199EF7E }}